### ISSUE TITLE
new lib ZUNO_MCP4725

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#106]
No idea how to make a pull request ;) ... so I add it here.
It was tested by a user in forum - so it seems to be ok.

Have modified a little bit the original lib.

An example is inside too.

[ZUNO_MCP4725.zip](https://github.com/Z-Wave-Me/Z-Uno-Core/files/614398/ZUNO_MCP4725.zip)

Michael

**Comment by p0lyg0n1** [comment]
Added to release 2.0.7
