### ISSUE TITLE
DS18B20 do not return negatve values - only 0.000 degree

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/Z-Uno-Core#107]

**Comment by michapr** [comment]
attached a corrected lib for 18b20 - it is working now for negative values.

Additional I have added the request for stored resolution and zero the undefined low bits for lower resolution.

Have tested with my outside and room temp - it is working as expected ;)

Michael
[ZUNO_DS18B20.zip](https://github.com/Z-Wave-Me/Z-Uno-Core/files/629363/ZUNO_DS18B20.zip)

**Comment by PoltoS** [comment]
Fixed in 2.0.9
