### ISSUE TITLE
Добавить описание названий ног к analogRead и analogWrite

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/Z-Uno-Core#12]

**Comment by PoltoS** [comment]
желательно их ещё и унифицировать. см #22

**Comment by NilsBohr** [comment]
Добавлены дефайны **A0, A1, A2, A3** для analogRead.
Добавлены дефайны **PWM1, PWM2, PWM3, PWM4** для analogWrite.

**Comment by OneMoreLera** [comment]
Исправлены примеры  на сайте для analogRead, analogWrite в соответствии с новыми дефайнами.
