### ISSUE TITLE
Ошибка компиляции демо скетчей

### ISSUE THREAD

**Issue by pastukhov** [Z-Wave-Me/Z-Uno-Core#17]
Arduino IDE 1.6.5, Z-Uno-Core 0.5.1

```
?ASlink-Warning-Undefined Global '_zunoDebugParameter' referenced by module 'Core_arduino'
```

**Comment by NilsBohr** [comment]
Добрый день. Спасибо. В версии 0.51 добавили новый макрос
ZUNO_SETUP_DEBUG_MODE(0 или 1)
Примеры не обновили,  проверку наличия не добавили,  исправимся. 

Добавьте в скетч этот макрос. Должно собраться.  В будущем он будет позволять на лету менять параметры частот,  классов и т. Д.

**Comment by pastukhov** [comment]
Спасибо!
Скомпилировалось.

**Comment by NilsBohr** [comment]
Fixed in 0.52.
Added preprocessor check for macro.
