### ISSUE TITLE
label:hardware Перенос usb разъема на верхнюю сторону платы

### ISSUE THREAD

**Issue by pastukhov** [Z-Wave-Me/Z-Uno-Core#32]
Если будет возможность, в следующих релизах прошу перенести разъем на верхнюю сторону платы. Так как при установке на монтажную плату досуп к разъему перекрывается.

**Comment by NilsBohr** [comment]
Исправлено в Z-Uno 3. Новое железо планируется на лето 2016 года

**Comment by pastukhov** [comment]
Спасибо!
