### ISSUE TITLE
USB in sleeping mode

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#46]
If device is in sleeping mode the USB port is not available for uploading new sketch.
Device should be waked up permanent before, then new sketch can be uploaded.

I think would be a good idea to add this to documentation.

**Comment by PoltoS** [comment]
Right, we need to document that for sleepingFLiRS devices upload should be done via Rescue mode

**Comment by PoltoS** [comment]
Added: http://z-uno.z-wave.me/Reference/ZUNO_SETUP_SLEEPING_MODE/
