### ISSUE TITLE
DEVICE in FLIRS mode - connection lost

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#50]
reference file for testing 
(same, but: ZUNO_SETUP_SLEEPING_MODE(ZUNO_SLEEPING_MODE_FREQUENTLY_AWAKE);):
http://www.zwave-review.com/files/MultiFunctionSensor.ino

after some seconds device will be "dead" in GUI - in log:

[2015-09-16 08:40:26.740] [I] [core] Notification: error (connection): Connection lost to Z-Wave device ID: 10

**Comment by PoltoS** [comment]
sure you excluded-included after changing mode to FLiRS?

----- Исходное сообщение -----

**Comment by michapr** [comment]
OF COURSE! And had to reset the device before. Device is shown in UI as FLIRS device.
I have all interview in log - had to reinitialize sometimes via force interview while all was ok.

**Comment by michapr** [comment]
problem seems to exist only after changing switch level. Transmission failed to "FLIRS" device, thats why this error (I think so)

**Comment by NilsBohr** [comment]
fixed in version 0.62
