### ISSUE TITLE
Missig predifined sensor types

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#52]
Please correct http://z-uno.z-wave.me/Reference/ZUNO_SENSOR_MULTILEVEL/  for now.
"Popular sensor types have pre-defined macro. Few are listed below. Full list is defined in Core_arduino.h file..."

Not all are ready - as sample 
ZUNO_SENSOR_MULTILEVEL_DISTANCE(getter)
ZUNO_SENSOR_MULTILEVEL_VOLTAGE(getter)
ZUNO_SENSOR_MULTILEVEL_CURRENT(getter)  ...

**Comment by NilsBohr** [comment]
Added in latest build
