### ISSUE TITLE
Serial1_Print_char still missing

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#55]
Please add in Core_arduino.c the missing function:

void Serial1_Print_char(BYTE value) {
    if (value >= 100)
            Serial1_Write((value / 100) + 0x30);
        if (value >= 10)
            Serial1_Write(((value / 10) % 10) + 0x30);
        Serial1_Write((value % 10) + 0x30);
}

**Comment by NilsBohr** [comment]
Thnx, will add it in 0.63
