### ISSUE TITLE
Ошибки в доке

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/Z-Uno-Core#58]
Битая ссылка из http://z-uno.z-wave.me/Reference/ZUNO_SETUP_CHANNELS/ на http://z-uno.z-wave.me/Reference/ZUNO_SENSOR_MULTILEVEL_TEMPERATURE/

Там же пример кривой (проверить - тот же макрос)

Там же не хватает ссылки на остальные базовые типы каналов (на все 4 нужны).

На стр. http://z-uno.z-wave.me/Reference/Z-Wave/ заменить ZUNO_SETUP_FREQUENCY на описание пункта меню.

**Comment by OneMoreLera** [comment]
всё исправила
