### ISSUE TITLE
OpenZwave /Fibaro HC2 problem

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#66]
Can you please recheck OpenZwave compatibility?

Device will be recognized (with id numbers) and included.
Open ZWave does not receive any value changes 
(for ZUNO_SENSOR_MULTILEVEL_TEMPERATURE, ZUNO_SENSOR_MULTILEVEL_GENERAL_PURPOSE, ...)

Nothing (no data) visible in OpenZwave Log.

Same sketch is working in Z-Way 2.2.1-rc4 fine.

In HC2 (v.4.070) device will be included full, but temperature values will not be transmitted.
Dimmer sample is working.

In both cases (OpenZwave and HC2) the actual (first) values will be shown - but not changed.

**Comment by NilsBohr** [comment]
Can you please retest your sketch with latest build? If it still doesn't work, will be great, if you can provide your sketch for tests.

**Comment by PoltoS** [comment]
Can we close this?

**Comment by michapr** [comment]
yes, will test with new version. Still the issue that no values in HC2 #85
