### ISSUE TITLE
Serial.parseFloat() crashes

### ISSUE THREAD

**Issue by danielboe** [Z-Wave-Me/Z-Uno-Core#74]
The parseFloat() and parseInt() function makes the zuno crash. only reset helps to make it available via serial for reprogramming.
sample code:

```
void setup() {
  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  Serial2.begin(9600);
  Serial.println("Init");
  Serial.println();
}

void loop() {
  // Read serial input:
  while (Serial2.available() > 0) {
    char inChar = Serial2.read();
    Serial.println(inChar);
    if (inChar == 'A') {
        for (int i = 1; i <=2; i++) {
          float test = Serial2.parseFloat();
          Serial.print("float: ");
          //Serial.println(test);
        }
      Serial.println("Select A");
    }
  }
}
```

**Comment by NilsBohr** [comment]
Thank you for your report.
What version are you using? 2.02?

**Comment by danielboe** [comment]
Ah sorry, I forgot. Its version 2.02, yes. Also itos() is not implemented, so I actually see no way to convert string->number. Thanks

**Comment by danielboe** [comment]
Here is a simple function to convert char-arrays to numbers:

```
int a2i(const char *s)
{
 int sign=1;
 if(*s == '-'){
  sign = -1;
  s++;
 }
 int num=0; //maybe double needed if greater values
 while(*s){
  num=((*s)-'0')+num*10;
  s++;   
 }
 return num*sign;
}
```

**Comment by NilsBohr** [comment]
Functions _parseInt()_ and _parseFloat()_ hangs Z-Uno in infinite loop. Stream lib must be rewritten to avoid busy loops and waiting.

**Comment by PoltoS** [comment]
Please try 2.0.3

**Comment by PoltoS** [comment]
Can we close it? Does it work now on 2.0.5?
