### ISSUE TITLE
CO2 sensor sample

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#78]
http://z-uno.z-wave.me/examples/CO2_sensor/

Funny expression - when this will be valid? ;)
 ...

`if ((ppm > (ppm + 100)) || (ppm < (ppm - 100)))`

better:
`int ppm1`
`...`
`ppm1 = (256*responseHigh) + responseLow; //for end result`
`  `
` if ((ppm1 > (ppm + 100)) || (ppm1 < (ppm - 100))){`
`  ppm=ppm1;`
`....`

Michael

**Comment by NilsBohr** [comment]
Thank you!

We have updated the sketch. Now it shall be working better
