### ISSUE TITLE
update from 2.0.2 to 2.0.3 error

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#80]
Hi,

can not update from 2.0.2 to 2.0.3 - get follwing error writing boot loader:
...
Writing NVM data                         [=================>                                ](35%)
Writing NVM data                         [=================>                                ](35%)Traceback (most recent call last):

  File "<string>", line 1149, in serial_api_fwfunc
  File "<string>", line 884, in reflashFirmware
  File "<string>", line 815, in writeFileToNVM
ProgrammerError: Can't write NVM data! at=39c00

or

ProgrammerError: Can't write NVM data! at=5d800
Error  0     Unknown exception:Can't write NVM data! at=5d800

Any idea?

Michael

**Comment by michapr** [comment]
after complete reset (there was a sketch inside) firmware update was possible.
Maybe make sense to add it to troubleshooting page?

Michael

**Comment by PoltoS** [comment]
Have you used USB in your sketch?

**Comment by michapr** [comment]
Do not understand what you mean, sorry.

Von: Poltorak Serguei [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Juli 2016 21:13
An: Z-Wave-Me/Z-Uno-Core
Cc: Michael P.; State change
Betreff: Re: [Z-Wave-Me/Z-Uno-Core] update from 2.0.2 to 2.0.3 error (#80)

Have you used USB in your sketch?

**Comment by PoltoS** [comment]
Your previous sketch did something that blocked Z-Uno bootlader from communications via USB. This is usually either some insane loop without delays or USB usage from sketch.

[Rescue mode](http://z-uno.z-wave.me/getting-started/troubleshooting#Z-UnoHangs) should help in both cases.

**Comment by michapr** [comment]
Hi,
no, no USB usage in sketch.

Loop without delays – yes. A delay should not be mandatory in a loop, right?

There were called 2 functions in loop 
First is looking for changes button state and increase counter if state was changed
Second will send every 60 seconds (if(currentTime >= (cloopTime + 60000)) )  the report request to Z-Uno.

Z-Uno was in ALWAYS_AWAKE mode.

So I really think nothing “critical” …

Best regards
Michael

Von: Poltorak Serguei [mailto:notifications@github.com] 
Gesendet: Montag, 18. Juli 2016 01:01
An: Z-Wave-Me/Z-Uno-Core
Cc: Michael P.; State change
Betreff: Re: [Z-Wave-Me/Z-Uno-Core] update from 2.0.2 to 2.0.3 error (#80)

Your previous sketch did something that blocked Z-Uno bootlader from communications via USB. This is usually either some insane loop without delays or USB usage from sketch.

Rescue mode http://z-uno.z-wave.me/getting-started/troubleshooting#Z-UnoHangs  should help in both cases.

**Comment by michapr** [comment]
I think outdated. can be closed
