### ISSUE TITLE
Z-Uno configuration parameters

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#88]
http://z-uno.z-wave.me/z-wave/configuration-parameters/

What is the parameter **name** - and how to use it?
Set as simple parameter in Arduino IDE?

Thanks

**Comment by PoltoS** [comment]
As mentioned on this page, these are parameters defined via Z-Wave Configuration CC

**Comment by PoltoS** [comment]
You can use any controller s/w to set them

**Comment by michapr** [comment]
ok... I was thinking about this part:
"Some configurations are made right in the user sketch in Arduino IDE, some are defined via Arduino IDE menu"

Thanks.
