### ISSUE TITLE
possible to store values in Flash?

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#91]
Is it possible to store values in Flash?
As sample a meter will count any value and reach 1000 units.
Somebody will reset the Z-Uno (or power fails) - then the meter will begin at "0" again.

Current meters will remember about last value and continue to count frome here.

Any idea?
Thanks!

**Comment by PoltoS** [comment]
https://z-uno.z-wave.me/Reference/EEPROM/
