### ISSUE TITLE
device dead

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#92]
using 2.0.4
use RadioBlink sample sketch
-> it is working stable
modify:
void setSwitchMultilevelValue(byte newValue) {
  char szTmp[100];
  Serial.print("SValue: ");
  Serial.println(newValue);
  //save new value in a variable
  dimmerValue = newValue;
}

Without "char szTmp[100];" all is woking fine - adding this line Z-Uno will be dead after some value changes via UI (Z-Way)
No other changes were made, it is reproducable.

Upload sketch without this line again - device will "come back".

**Comment by PoltoS** [comment]
This looks like a known and already fixed problem. Please wait for 2.0.5.
