### ISSUE TITLE
DS18B20 sample 1Wire

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#95]
I'm a little bit confused about the 220 Ohm resistor.
Is it true - or a mistake?
http://z-uno.z-wave.me/examples/1-wire-ds18b20-temperature-sensor/
look here:
https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf
-> 4.7 kOhm

**Comment by PoltoS** [comment]
indeed recommended is 4.7k. Updated. Thanks. Though I don't think it is really important. 

PS 

----- Исходное сообщение -----

**Comment by michapr** [comment]
> Though I don't think it is really important.

it is...
"Digital pin out logical 0: < 0.4 V, max current sinking 8 mA"
-> 2,9V / 220 Ohm = 13.2 mA  really too much for such an application

Even not sure will it be fine for DS18B20 with such a current on output.
Never have used R<2kOhm for 1-Wire - even for long lines... ;)
