### ISSUE TITLE
18B20 usage

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#98]
How to request multiple 18B20 on same OneWire line?

In most cases there are multiple sensors on one line - that's why there should be a function for looking for address of the 18B20 - and using this address the sensor value will be requested.

Using 2 sensors (parallel) in this time will not work.

Maybe you can prvide a sample code using your lib?

Thanks!
Michael

**Comment by p0lyg0n1** [comment]
In current version you can do it if you know uid(rom) of your sensors. You can scan its rom when sensor connect to bus alone and then use it to get its value when you have many sensors connected to the bus. We will provide full search procedure for OneWire in the next releases.

**Comment by michapr** [comment]
ok, then you can close the issue - maybe add any hint in code comment section?
