### ISSUE TITLE
missing lib in samples

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#99]
in samples is the new library missing.
http://z-uno.z-wave.me/examples/1-wire-ds18b20-temperature-sensor/
http://z-uno.z-wave.me/examples/onewire-temperature-sensor-ds18b20-and-i2c-lcd-display/

**wrong:**
`// add library ds18b20`
`#include`
` `
`// pin connection ds18b20`

**right:**
`...`
`#include "ZUNO_DS18B20.h"`

**Comment by PoltoS** [comment]
thanks, fixed. <> were interpreted as tags ;)
